Jahia/copy-to-other-languages

package.json
pom.xml
src/javascript/CopyToOtherLanguages/CopyToOtherLanguages.gql.js
src/javascript/CopyToOtherLanguages/CopyToOtherLanguages.jsx
src/javascript/CopyToOtherLanguages/CopyToOtherLanguagesActionComponent.jsx
tests/cypress/integration/copyLanguages.ts
tests/cypress/page-object/edit.page.ts
tests/cypress/page-object/threeDots.button.ts
tests/package.json
tests/provisioning-manifest-build.yml
tests/yarn.lock
yarn.lock

https://jira.jahia.org/browse/BACKLOG-17162
Update copy-to functionality so that value being copied to is copied to the form (through `setI18nContext`) instead of being saved directly for each language.
Also enable functionality during create

BACKLOG-17162: Update copy-to language values without saving

---

.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
package.json
pom.xml
webpack.config.js
yarn.lock

https://jira.jahia.org/browse/TECH-1275
Add cyclonedx-maven-plugin and create/upload SBOMs on merge and release

TECH-1275: Add SBOM creation

---

pom.xml

https://jira.jahia.org/browse/TECH-1275
Add cycloned.skip for dev profiles

TECH-1275: Add cycloned.skip for dev profiles

---

package.json
pom.xml
src/javascript/CopyToOtherLanguages/CopyToOtherLanguagesActionComponent.jsx
tests/provisioning-manifest-build.yml
tests/provisioning-manifest-snapshot.yml
webpack.config.js

https://jira.jahia.org/browse/BACKLOG-20402

BACKLOG-20402: Update content-editor import; bump version

---

.github/workflows/on-merge.yml
tests/cypress/e2e/copyLanguages.cy.ts
tests/cypress/page-object/jcontent.ts

https://jira.jahia.org/browse/BACKLOG-20402
Add switch to list mode since default view changed now to page builder

BACKLOG-20402: Fix cypress tests

---

.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml

https://jira.jahia.org/browse/BACKLOG-20402

BACKLOG-20402: Fix versions

---

.github/workflows/nightly.yml

TECH-1415: Fixed incorrect use of the matrix

---

.github/workflows/nightly.yml

Split pagerduty reporting between Jahia Snapshot and Jahia Release

---

.github/workflows/manual-run.yml
.github/workflows/nightly.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/on-release.yml
.github/workflows/schedule-sonar.yml
tests/.env.example
tests/cypress/e2e/copyLanguages.cy.ts
tests/env.run.sh
tests/provisioning-manifest-build.yml
tests/provisioning-manifest-snapshot.yml

- Updated docker image
- Updated the list of modules to be installed (using fixed version)
- Cleaned incorrect workflow parameters
- Minor tweak in the test
- Fixed an incorrect configuration for fetching the list of module (was in error before)

TECH-1657: Replace jahia-discovery with jahia-ee

---

.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/schedule-sonar.yml
pom.xml
tests/assets/ctol-definitions/pom.xml

https://jira.jahia.org/browse/BACKLOG-21778

BACKLOG-21778: Prepare release

---

.github/workflows/on-release.yml

https://jira.jahia.org/browse/BACKLOG-21778

BACKLOG-21778: Fixed a checkout issue preventing the release

---

pom.xml
src/javascript/CopyToOtherLanguages/CopyToOtherLanguagesActionComponent.jsx
tests/cypress.config.ts
tests/cypress/e2e/copyLanguages.cy.ts
tests/cypress/fixtures/utils.ts

https://jira.jahia.org/browse/BACKLOG-22741

BACKLOG-22741: Disable menu item when node is locked

---

.github/workflows/manual-run.yml
.github/workflows/nightly.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
pom.xml
src/javascript/CopyToOtherLanguages/CopyToOtherLanguagesActionComponent.jsx
tests/.env.example
tests/ci.build.sh
tests/cypress/fixtures/graphql/jcr/deployModule.graphql
tests/cypress/fixtures/graphql/jcr/undeployModule.graphql
tests/cypress/integration/copyLanguages.ts

https://jira.jahia.org/browse/BACKLOG-22516
2.1.0-SN backport for PR https://github.com/Jahia/copy-to-other-languages/pull/29

BACKLOG-22516: Check if module is deployed on current site

---

.github/workflows/on-release.yml

https://jira.jahia.org/browse/BACKLOG-22515

BACKLOG-22515: Fix release wf

---

.github/workflows/nightly-RL.yml
.github/workflows/nightly-SN.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml

https://jira.jahia.org/browse/TECH-1480

TECH-1480: Re-enabled nightly tests with Jahia release

---

pom.xml
src/javascript/CopyToOtherLanguages/CopyToOtherLanguagesActionComponent.jsx

https://jira.jahia.org/browse/QA-15315

QA-15315 Backport of clearing properties feature

---

pom.xml

https://jira.jahia.org/browse/QA-15315

QA-15315 Version bump & dependency versions

---

pom.xml

https://jira.jahia.org/browse/QA-15315

QA-15315 Removed duplicate dependency declaration

---

pom.xml

QA-15315 Correct version bump to 3.1.1

---

tests/provisioning-manifest-build.yml
tests/provisioning-manifest-snapshot.yml

QA-15315 Updated provisioning

---

pom.xml

https://jira.jahia.org/browse/BACKLOG-23565
Update parent version to 8.1.3.0.

Update parent version to 8.1.3.0

---

tests/Dockerfile
tests/package.json
tests/yarn.lock

[jira.jahia.org/browse/QABACKLOG-1661](https://jira.jahia.org/browse/QABACKLOG-1661)

QABACKLOG-1661: Upgraded cypress base image

---

pom.xml
src/javascript/CopyToOtherLanguages/CopyAllToOtherLanguagesActionComponent.jsx
src/javascript/CopyToOtherLanguages/CopyToOtherLanguages.gql.js
src/javascript/CopyToOtherLanguages/CopyToOtherLanguages.jsx
src/javascript/CopyToOtherLanguages/WarningAlert.jsx
src/javascript/CopyToOtherLanguages/register.jsx
src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json
tests/cypress/page-object/threeDots.button.ts

Backport of the copy all properties to all languages feature

---

.github/workflows/on-merge.yml
tests/cypress/page-object/threeDots.button.ts

chore: skip tests for module publishing in 2.x branch

---

pom.xml

Updating jahia-parent as per release minimum jahia version https://github.com/Jahia/copy-to-other-languages/issues/85

build: Update jahia-parent version

---

src/main/resources/javascript/locales/de.json
src/main/resources/javascript/locales/en.json
src/main/resources/javascript/locales/fr.json

feat: shorter labels for actions in de / en / fr

---

.github/workflows/manual-run.yml
.github/workflows/nightly-RL.yml
.github/workflows/nightly-SN.yml
.github/workflows/on-code-change.yml
.github/workflows/on-merge.yml
.github/workflows/schedule-sonar.yml
tests/.env.example

chore: migrate to gh packages
